server:
  port: 8080

grpc:
  server:
    port: 59091

spring:
  application:
    name: collector
  config:
    import: "optional:configserver:http://localhost:8888"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.collector.broker.CollectorAvroSerializer

logging:
  level:
    ru.yandex.practicum.collector: DEBUG