spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # оставляем none, чтобы не мешать schema.sql
    show-sql: true
    defer-datasource-initialization: true  # ВАЖНО: schema.sql выполнится после настройки Hibernate
  sql:
    init:
      mode: always  # всегда выполнять скрипты инициализации
      platform: postgresql
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG