spring.sql.init.mode=never

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/smart_home
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
custom.kafka.bootstrap-servers=localhost:9092

custom.kafka-snapshot.bootstrap-servers=${custom.kafka.bootstrap-servers}
custom.kafka-snapshot.snapshot-consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
custom.kafka-snapshot.snapshot-consumer.value-deserializer=ru.yandex.practicum.analyzer.broker.SensorsSnapshotDeserializer
custom.kafka-snapshot.snapshot-consumer.auto-offset-reset=earliest
custom.kafka-snapshot.snapshot-consumer.group-id=analyzer-snapshot-group

custom.kafka-hub-event.bootstrap-servers=${custom.kafka.bootstrap-servers}
custom.kafka-hub-event.hub-event-consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
custom.kafka-hub-event.hub-event-consumer.value-deserializer=ru.yandex.practicum.analyzer.broker.HubEventDeserializer
custom.kafka-hub-event.hub-event-consumer.auto-offset-reset=earliest
custom.kafka-hub-event.hub-event-consumer.group-id=analyzer-hub-group

grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

spring.application.name=analyzer
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.useRandomPolicy=true
spring.cloud.config.retry.max-interval=6000