package ru.yandex.practicum.api.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorType {
    DELIVERY_NOT_FOUND("DELIVERY_NOT_FOUND"),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND"),
    PAYMENT_NOT_FOUND("PAYMENT_NOT_FOUND"),
    CART_NOT_FOUND("CART_NOT_FOUND"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
    NOT_ENOUGH_INFO("NOT_ENOUGH_INFO"),
    NOT_AUTHORIZED("NOT_AUTHORIZED"),
    NO_PRODUCTS_IN_CART("NO_PRODUCTS_IN_CART"),
    PRODUCT_NOT_IN_WAREHOUSE("PRODUCT_NOT_IN_WAREHOUSE"),
    PRODUCT_ALREADY_IN_WAREHOUSE("PRODUCT_ALREADY_IN_WAREHOUSE"),
    LOW_QUANTITY_IN_WAREHOUSE("LOW_QUANTITY_IN_WAREHOUSE"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String code;
}